api_platform:
    title: 'Bilemo With Api Platform'
    description: 'A simple Api With Api-Platform'
    version: '1.0.0'
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/config/api_platform'
    formats:
        html:     ['text/html']
        jsonhal:  ['application/hal+json']