App\Entity\Product:
  collectionOperations:
    get: ~ # nothing more to add if we want to keep the default controller
  itemOperations:
    get:
        method: 'GET'
        requirements:
          id: '\d+'